In [1]:
# Q1. List any five functions of the pandas library with execution.
# A1. 
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
print(data)
print(data.head())
print(data.info())
print(data.describe())
print(data.columns)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [2]:
# Q2. Given a Pandas DataFrame df with columns 'A', 'B', and 'C', write a Python function to re-index the
#     DataFrame with a new index that starts from 1 and increments by 2 for each row.
df=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10],"C":[11,12,13,14,15]})
def rIndex():
    l=[]
    for i in range(1,10,2):
        l.append(i)
    return l
df.index=rIndex()
df

   A   B   C
1  1   6  11
3  2   7  12
5  3   8  13
7  4   9  14
9  5  10  15

In [3]:
# Q3. You have a Pandas DataFrame df with a column named 'Values'. Write a Python function that
#     iterates over the DataFrame and calculates the sum of the first three values in the 'Values' column. The
#     function should print the sum to the console.
df=pd.DataFrame({"Values":[10,20,30,40,50],"num":[6,7,8,9,10]})

def sum(df):
    sum=0
    for i in range(0,3):
        sum=sum+df["Values"][i]
    
    return sum

sumA=sum(df)
print(sumA)

60

In [4]:
# Q4. Given a Pandas DataFrame df with a column 'Text', write a Python function to create a new column
#     'Word_Count' that contains the number of words in each row of the 'Text' column.
df=pd.DataFrame({"Text":["Hello Python","Hello Python is great","Python is a good programming language",""]})

def wordCount(df):
    l=[]
    length=len(df)
    for i in range(0,length):
        ele=df["Text"][i]
        l.append(len(ele.split()))
    
    df["Word_count"]=l
    return df
    

df=wordCount(df)
df

                                    Text  Word_count
0                           Hello Python           2
1                  Hello Python is great           4
2  Python is a good programming language           6
3                                                  0

In [5]:
# Q5. How are DataFrame.size() and DataFrame.shape() different?
df=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10],"C":[11,12,13,14,15]})
print(df)
print("\n")
print("Dataframe.size() :",df.size)
print("\n")
print("DataFrame.shape() :",df.shape)
# As we can see the DataFrame.size() function displays the number of elements present in a Dataframe while the 
# dataFrame.shape() function gives us the number of rows and the number of coloumns in the DataFrame

   A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15


Dataframe.size() : 15


DataFrame.shape() : (5, 3)

In [6]:
# Q6. Which function of pandas do we use to read an excel file?
# A6. pd.read_excel("File Name here") is the function that we use to read an excel file using pandas.

In [7]:
# Q7. You have a Pandas DataFrame df that contains a column named 'Email' that contains email
#     addresses in the format 'username@domain.com'. Write a Python function that creates a new column
#     'Username' in df that contains only the username part of each email address.
import re
df=pd.DataFrame({"Email":["shaurya@g.com","shrey@mail.com","manu@outlook.com"]})

def username(df):
    r_num=df.shape[0]
    l=[]
    for i in range(0,r_num):
        email=df["Email"][i]
        pattern = r"^([^@]+)@"
        match = re.search(pattern, email)
        uname = match.group(1)
        l.append(uname)
    
    df["Username"]=l
    return df
        
        

df=username(df)
df

              Email Username
0     shaurya@g.com  shaurya
1    shrey@mail.com    shrey
2  manu@outlook.com     manu

In [8]:
# Q8. You have a Pandas DataFrame df with columns 'A', 'B', and 'C'. Write a Python function that selects
#     all rows where the value in column 'A' is greater than 5 and the value in column 'B' is less than 10. The
#     function should return a new DataFrame that contains only the selected rows.
df=pd.DataFrame({"A":[3,8,6,2,9],"B":[5,2,9,3,1],"C":[1,7,4,5,2]})

def func(df):
    n_rows=df.shape[0]
    l=[]
    for i in range(0,n_rows):
        a=df["A"][i]
        b=df["B"][i]
        if(a>5 and b<10):
            l.append(i)
    
    
    length=len(l)
    l1=[]
    l2=[]
    l3=[]
    for i in range(0,length):
        l1.append(df["A"][l[i]])
        l2.append(df["B"][l[i]])
        l3.append(df["C"][l[i]])
        
    df1=pd.DataFrame({"A":l1,"B":l2,"C":l3})
    return df1
        

print(df,"\n")
df1=func(df)
df1

   A  B  C
0  3  5  1
1  8  2  7
2  6  9  4
3  2  3  5
4  9  1  2

   A  B  C
0  8  2  7
1  6  9  4
2  9  1  2

In [9]:
# Q9. Given a Pandas DataFrame df with a column 'Values', write a Python function to calculate the mean,
#     median, and standard deviation of the values in the 'Values' column.
df=pd.DataFrame({"Values":[10,20,30,40,50]})

def func(df):
    mean=df.mean()
    median=df.median()
    sd=df.std()
    
    print("Mean of the data is:",mean[0])
    print("Median of the data is:",median[0])
    print("Standard Deviation of the data is:",sd[0])

func(df)

Mean of the data is: 30.0
Median of the data is: 30.0
Standard Deviation of the data is: 15.811388300841896

In [11]:
# Q11. You have a Pandas DataFrame df with a column 'Date'. Write a Python function that creates a new
#      column 'Weekday' in the DataFrame. The 'Weekday' column should contain the weekday name (e.g.
#      Monday, Tuesday) corresponding to each date in the 'Date' column.
import datetime

a = datetime.datetime(2024, 8, 24)
b = datetime.datetime(2024, 8, 25)
c = datetime.datetime(2024, 8, 26)
d = datetime.datetime(2024, 8, 27)
e = datetime.datetime(2024, 8, 28)

df=pd.DataFrame({"Date":[a,b,c,d,e]})

def weekday(df):
    n_rows=df.shape[0]
    l=[]
    for i in range(0,n_rows):
        x=df["Date"][i]
        l.append(x.strftime("%A"))
    
    df["Weekday"]=l
    return df
        

df=weekday(df)
df

        Date    Weekday
0 2024-08-24   Saturday
1 2024-08-25     Sunday
2 2024-08-26     Monday
3 2024-08-27    Tuesday
4 2024-08-28  Wednesday

In [12]:
# Q12. Given a Pandas DataFrame df with a column 'Date' that contains timestamps, write a Python
#      function to select all rows where the date is between '2023-01-01' and '2023-01-31'.
import datetime
x=a.strftime("%A")
a = datetime.datetime(2023, 1, 24)
b = datetime.datetime(2023, 1, 25)
c = datetime.datetime(2023, 3, 26)
d = datetime.datetime(2023, 2, 27)
e = datetime.datetime(2023, 1, 28)

df=pd.DataFrame({"Date":[a,b,c,d,e]})

def date(df):
    s_date=datetime.datetime(2023, 1, 1)
    e_date=datetime.datetime(2023, 1, 31)
    n_rows=df.shape[0]
    l=[]
    for i in range(0,n_rows):
        x=df["Date"][i]
        if(x>s_date and x<e_date):
            l.append(i)
            
    return l
            

print("The rows where the Date lies between the given constraints are:",date(df))
df

The rows where the Date lies between the given constraints are: [0, 1, 4]

        Date
0 2023-01-24
1 2023-01-25
2 2023-03-26
3 2023-02-27
4 2023-01-28

In [13]:
# Q13. To use the basic functions of pandas, what is the first and foremost necessary library that needs to
#      be imported?
# A13. Numpy